/*inserts 28 cells of data into ingredients*/
INSERT INTO tbl_ingredients(ingredient_ID, contains_allergen , ingredient)
VALUES
(1, 1, 'cereal (wheat, rye, barely, oats)'),
(2, 1, 'crustaceans (prawns, lobster, and crayfish)'),
(3, 1, 'eggs'),
(4, 1, 'fish'),
(5, 1, 'peanuts'),
(6, 1, 'soybeans'),
(7, 1, 'milk (including lactose)'),
(8, 1, 'nuts (almonds, hazelnuts, walnuts, cashews, pecan nuts, brazil nuts, pistachio nuts, and macadamia)'),
(9, 1, 'celery (including celeriac)'),
(10, 1, 'mustard'), 
(11, 1, 'sesame'),
(12, 1, 'sulphur dioxide / sulphites, where added and at a level above 10mg/kg or 10mg/L in the finished product. This can be used as a preservative in dried fruit'),
(13, 1, 'lupin, which includes lupin seeds and flour and can be found in types of bread, pastries and pasta'),
(14, 1, 'molluscs like, mussels, whelks, oysters, snails and squid'),
(15, 0, 'tahini'),
(16, 0, 'banana'),
(17, 0, 'chicken breast'),
(18, 0, 'lemon'),
(19, 0, 'cayenne pepper'),
(20, 0, 'sesame seeds'),
(21, 0, 'lamb mince'),
(22, 0, 'thyme'),
(23, 0, 'olive oil'),
(24, 0, 'za''tar'),
(25, 0, 'chickpeas'),
(26, 0, 'tabbouleh'),
(27, 0, 'sumac'),
(28, 0, 'sugar');
